### ISSUE TITLE
home page is bugged, even with only stylus + btroblox

### ISSUE THREAD

**Issue by junnlives** [sayorisocks/robsblocks#22]
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/debc8fa2-3edb-4649-aaa2-87da79effdaa)
title
i do not have any other styles enabled for stylus, just the 2014-esque
idk where else to report issues all i could find was this github repository

**Comment by tsukinousako** [comment]
this is hopefully fixed now, ty!

**Comment by junnlives** [comment]
hiya - this seems to still be broken as i tested again with just the 2 extensions needed and the home page is still messed up
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/34a9e065-39a8-43ed-8abb-30ac465ac2b3)
(i closed the friends list in this image)

edit:
i just updated from 1.3.7 to 1.3.9 and it still seems to be broken

**Comment by tsukinousako** [comment]
🫠

try updating to 1.4.0 and see if it's still broken

**Comment by junnlives** [comment]
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/9a59f4b9-be38-47b9-ac82-2ea0c1afd65c)
unfortunately still broken, on 1.4.0

Version 1.67.116 Chromium: 126.0.6478.71 (Official Build) (64-bit](https://brave.com/latest/) if that's anything

**Comment by tsukinousako** [comment]
🫠🫠

should work fine now?? try updating to 1.4.1, i've tested on brave and it works fine, if it doesn't then i have no clue

**Comment by junnlives** [comment]
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/a1c5cc66-5293-4b41-9487-1a599552ab42)
i have absolutely no idea either, i do have the new wide home page so that might be a factor but i don't know
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/5c13415e-7583-4472-8260-a2c9d2488994)

**Comment by tsukinousako** [comment]
try updating to 1.4.2 and see if it works now

**Comment by junnlives** [comment]
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/a2b78e72-3730-49ab-81f9-40f97c1033a0)
still doesn't work unfortunately, if it's anything i tested it on chrome aswell on an alt (with extensions) and it still happens
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/ad302cae-fab2-4f87-898a-ef462c5886a0)

**Comment by tsukinousako** [comment]
sorry for making you update so many times but try updating to 1.4.3, that should hopefully fix ur problems 😭

**Comment by junnlives** [comment]
unfortunately it did not 😭
i don't mind updating this many times, i should be apologizing to you instead
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/00dd63e5-b2dc-4a4f-b947-32f6d710cf6f)
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/fd93ff41-459b-4419-99d7-0001bbfc5a62)
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/9f5c81cd-080d-4558-92f2-0035b1aa5604)
here's my btroblox and stylus version if that even helps

**Comment by tsukinousako** [comment]
try 1.4.4?

**Comment by junnlives** [comment]
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/c34b334d-19e9-4ba8-960f-0a89cede6dce)
still broken :(

**Comment by tsukinousako** [comment]
looks fine to me

**Comment by junnlives** [comment]
oh it's supposed to look like this? i thought it was always meant to be like the previous versions (the one where the friendslist isnt vertical)
that's an eye-opener, i guess i'll have to live with it then considering this is closer to 2013

**Comment by junnlives** [comment]
it would be awesome if there was support for an avatar section like in this image though
![image](https://github.com/sayorisocks/robsblocks/assets/69032098/5dea12ce-58a7-4e6a-b1bc-b12147fc1fd5)

**Comment by tsukinousako** [comment]
you can use rogold or use [tersiswilvin's legacy site script ](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/blob/Release/Dev/Master/src/JS/LegacySiteRestoration.user.js)to get the avatar image

**Comment by junnlives** [comment]
thank you very much for fixing the home page + showing me that userscript, i really appreciate it and never knew something like this existed. once again, thank you!
